spring:
  sql:
    init:
      mode:
        never
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/DataBaseName
    username: OwnerOfDatabase
    password: PasswordOfOwner
    driver-class-name: org.postgresql.Driver