INSERT INTO QUESTION (ID, QUESTION_TEXT, A, B, C, D, CORRECT_ANSWER) VALUES
(10, 'What is the square root of 64?', '6', '8', '7', '9', 'B'),
(11, 'Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'Thailand', 'South Korea', 'B'),
(12, 'Who painted the Mona Lisa?', 'Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Claude Monet', 'B'),
(13, 'What is the chemical symbol for water?', 'O2', 'H2O', 'CO2', 'HO', 'B'),
(14, 'Who wrote "Pride and Prejudice"?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'C'),
(15, 'What is the largest planet in our solar system?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'C'),
(16, 'Which element has the atomic number 1?', 'Oxygen', 'Hydrogen', 'Helium', 'Carbon', 'B'),
(17, 'What is the capital of Australia?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 'B'),
(18, 'Who developed the theory of relativity?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking', 'B'),
(19, 'What is the boiling point of water in Celsius?', '100', '0', '50', '200', 'A'),
(20, 'Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars', 'A'),
(21, 'Who was the first president of the United States?', 'Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams', 'B'),
(22, 'What is the main language spoken in Brazil?', 'Spanish', 'Portuguese', 'French', 'English', 'B'),
(23, 'What is the largest mammal on Earth?', 'Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus', 'B'),
(24, 'What is the smallest unit of life?', 'Organ', 'Cell', 'Atom', 'Tissue', 'B'),
(25, 'Who discovered penicillin?', 'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 'B'),
(26, 'Which continent is the Sahara Desert located on?', 'Asia', 'Africa', 'Australia', 'Europe', 'B'),
(27, 'What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 'B'),
(28, 'Which gas do plants use for photosynthesis?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Methane', 'B'),
(29, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Fe', 'Pb', 'A'),
(30, 'What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B'),
(31, 'Who was the first man to step on the Moon?', 'Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Michael Collins', 'B'),
(32, 'What is the hardest natural substance on Earth?', 'Iron', 'Diamond', 'Gold', 'Graphite', 'B'),
(33, 'Which planet has the most moons?', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'B'),
(34, 'What is the capital of Italy?', 'Venice', 'Milan', 'Rome', 'Florence', 'C'),
(35, 'What is the chemical formula for table salt?', 'NaCl', 'KCl', 'H2SO4', 'NH3', 'A'),
(36, 'What does DNA stand for?', 'Deoxynucleic Acid', 'Deoxyribonucleic Acid', 'Ribonucleic Acid', 'Deoxyribose Nucleic Acid', 'B'),
(37, 'Which country is the largest by area?', 'Canada', 'Russia', 'China', 'United States', 'B'),
(38, 'What is the primary ingredient in guacamole?', 'Tomato', 'Avocado', 'Onion', 'Lime', 'B'),
(39, 'Which organ is responsible for pumping blood in the human body?', 'Lungs', 'Heart', 'Liver', 'Kidneys', 'B'),
(40, 'What is the speed of light in a vacuum?', '299,792 km/s', '300,000 km/s', '299,000 km/s', '250,000 km/s', 'A'),
(41, 'Who wrote "1984"?', 'Aldous Huxley', 'George Orwell', 'J.K. Rowling', 'Mark Twain', 'B'),
(42, 'What is the capital of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'A'),
(43, 'What is the process by which plants make food?', 'Respiration', 'Photosynthesis', 'Transpiration', 'Digestion', 'B'),
(44, 'Which country won the FIFA World Cup in 2018?', 'Germany', 'Brazil', 'France', 'Argentina', 'C'),
(45, 'Who is known as the Father of Computers?', 'Alan Turing', 'Charles Babbage', 'John von Neumann', 'Steve Jobs', 'B'),
(46, 'What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Nagoya', 'A'),
(47, 'Which gas is most abundant in Earth’s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Helium', 'B'),
(48, 'What is the national flower of India?', 'Rose', 'Lotus', 'Jasmine', 'Sunflower', 'B'),
(49, 'What is the square of 12?', '124', '144', '132', '122', 'B'),
(50, 'Who painted "Starry Night"?', 'Claude Monet', 'Vincent van Gogh', 'Pablo Picasso', 'Salvador Dalí', 'B'),
(51, 'What is the currency of the United Kingdom?', 'Euro', 'Pound Sterling', 'Dollar', 'Franc', 'B'),
(52, 'Which is the tallest mountain in the world?', 'K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse', 'B'),
(53, 'What is the smallest planet in our solar system?', 'Mercury', 'Mars', 'Venus', 'Pluto', 'A'),
(54, 'Who wrote "The Odyssey"?', 'Homer', 'Socrates', 'Plato', 'Aristotle', 'A'),
(55, 'What is the study of weather called?', 'Geology', 'Meteorology', 'Biology', 'Astronomy', 'B'),
(56, 'What is the freezing point of water in Fahrenheit?', '32', '0', '100', '212', 'A'),
(57, 'Which planet is tilted on its side?', 'Jupiter', 'Uranus', 'Neptune', 'Saturn', 'B'),
(58, 'What is the chemical symbol for iron?', 'Ir', 'Fe', 'I', 'In', 'B');
